# Generated by Django 2.2.19 on 2022-07-15 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
