# Generated by Django 2.2.19 on 2022-07-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20220713_1612'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_user_recipe',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe'),
        ),
    ]
